INSERT INTO iterations (agent,task_id,status,notes) VALUES ('sanhedrin','EMAIL-CHECK','skip','GitHub notifications Gmail query from:notifications@github.com subject:"Run failed" newer_than:1h not executed: MCP returned user cancelled twice.');
INSERT INTO iterations (agent,task_id,status,notes) VALUES ('sanhedrin','CI-CHECK','warning','gh run list blocked by network: api.github.com unreachable for TempleOS(codex/modernization-loop) and holyc-inference(main).');
INSERT INTO iterations (agent,task_id,status,notes) VALUES ('sanhedrin','VM-CHECK','warning','Azure compile DB probe blocked: ssh to 52.157.85.234 port 22 operation not permitted; compile status unknown.');
INSERT INTO iterations (agent,task_id,status,notes) VALUES ('sanhedrin','AUDIT','warning','loops_alive_by_heartbeat(mod=1s inf=2s san=4s); recent_builder_pass_20(mod=20/20 inf=20/20); fail_streak5plus(mod=0 inf=0); task_repeat_streak_ge3(mod=0 inf=0); law5_code_output(mod_hc_sh_last5=5 inf_hc_last5=13); law1_core_nonholyc_hits=0; law2_network_diff_hits=0; law4_float_hits=111(info); law6_open_cq=58(>=25); secure_local_default=ok; gpu_iommu_book_of_truth_gates=ok; quarantine_hash_gate=ok; trinity_policy_parity=ok; split_plane_attestation_digest_gates=ok; ci_status=unknown_network_blocked; email_status=unknown_mcp_cancelled; azure_compile_status=unknown_network_blocked.');
INSERT INTO iterations (agent,task_id,status,notes) VALUES ('sanhedrin','EMAIL-CHECK','skip','GitHub notifications Gmail query from:notifications@github.com subject:"Run failed" newer_than:1h blocked: MCP returned user cancelled twice.');
INSERT INTO iterations (agent,task_id,status,notes) VALUES ('sanhedrin','CI-CHECK','warning','gh run list blocked: cannot connect to api.github.com for TempleOS(codex/modernization-loop) and holyc-inference(main); failed-run log triage unavailable.');
INSERT INTO iterations (agent,task_id,status,notes) VALUES ('sanhedrin','VM-CHECK','warning','Azure compile status blocked: ssh azureuser@52.157.85.234 denied (Operation not permitted).');
INSERT INTO iterations (agent,task_id,status,notes) VALUES ('sanhedrin','CLEANUP','pass','cleanup_old_audit_md_deleted=0.');
INSERT INTO iterations (agent,task_id,status,notes) VALUES ('sanhedrin','AUDIT','warning','loops_heartbeat_fresh(mod<=120s inf<=120s san<=120s); ps_liveness_check_blocked_by_sandbox; recent_builder_pass_20(mod=20/20 inf=20/20); fail_streak5plus(mod=0 inf=0); same_task_streak_ge3(mod=0 inf=0); builder_code_rows_last20(mod=20 inf=20); law5_mod_hc_sh_last5=5(pass); law5_inf_hc_last5=1(pass); law1_nonholyc_core(mod=0 inf=0); law2_network_diff_hits=0; law4_float_hits=111(info); law6_open_cq=58(>=25); secure_local_default=ok; quarantine_hash_gate=ok; gpu_iommu_book_of_truth_gates=ok; trinity_policy_parity=ok; split_plane_attestation_policy_digest_gates=ok; inference_network_enable_path=none; ci_check=blocked; email_check=blocked; azure_vm_check=blocked.');
