INSERT INTO iterations (agent,task_id,status,notes) VALUES ('sanhedrin','EMAIL-CHECK','skip','GitHub notifications Gmail query from:notifications@github.com subject:"Run failed" newer_than:1h not executed: MCP returned user cancelled twice.');
INSERT INTO iterations (agent,task_id,status,notes) VALUES ('sanhedrin','CI-CHECK','warning','gh run list blocked by network: api.github.com unreachable for TempleOS(codex/modernization-loop) and holyc-inference(main).');
INSERT INTO iterations (agent,task_id,status,notes) VALUES ('sanhedrin','VM-CHECK','warning','Azure compile DB probe blocked: ssh to 52.157.85.234 port 22 operation not permitted; compile status unknown.');
INSERT INTO iterations (agent,task_id,status,notes) VALUES ('sanhedrin','AUDIT','warning','loops_alive_by_heartbeat(mod=1s inf=2s san=4s); recent_builder_pass_20(mod=20/20 inf=20/20); fail_streak5plus(mod=0 inf=0); task_repeat_streak_ge3(mod=0 inf=0); law5_code_output(mod_hc_sh_last5=5 inf_hc_last5=13); law1_core_nonholyc_hits=0; law2_network_diff_hits=0; law4_float_hits=111(info); law6_open_cq=58(>=25); secure_local_default=ok; gpu_iommu_book_of_truth_gates=ok; quarantine_hash_gate=ok; trinity_policy_parity=ok; split_plane_attestation_digest_gates=ok; ci_status=unknown_network_blocked; email_status=unknown_mcp_cancelled; azure_compile_status=unknown_network_blocked.');
INSERT INTO iterations (agent,task_id,status,notes) VALUES ('sanhedrin','EMAIL-CHECK','skip','GitHub notifications Gmail query from:notifications@github.com subject:"Run failed" newer_than:1h blocked: MCP returned user cancelled twice.');
INSERT INTO iterations (agent,task_id,status,notes) VALUES ('sanhedrin','CI-CHECK','warning','gh run list blocked: cannot connect to api.github.com for TempleOS(codex/modernization-loop) and holyc-inference(main); failed-run log triage unavailable.');
INSERT INTO iterations (agent,task_id,status,notes) VALUES ('sanhedrin','VM-CHECK','warning','Azure compile status blocked: ssh azureuser@52.157.85.234 denied (Operation not permitted).');
INSERT INTO iterations (agent,task_id,status,notes) VALUES ('sanhedrin','CLEANUP','pass','cleanup_old_audit_md_deleted=0.');
INSERT INTO iterations (agent,task_id,status,notes) VALUES ('sanhedrin','AUDIT','warning','loops_heartbeat_fresh(mod<=120s inf<=120s san<=120s); ps_liveness_check_blocked_by_sandbox; recent_builder_pass_20(mod=20/20 inf=20/20); fail_streak5plus(mod=0 inf=0); same_task_streak_ge3(mod=0 inf=0); builder_code_rows_last20(mod=20 inf=20); law5_mod_hc_sh_last5=5(pass); law5_inf_hc_last5=1(pass); law1_nonholyc_core(mod=0 inf=0); law2_network_diff_hits=0; law4_float_hits=111(info); law6_open_cq=58(>=25); secure_local_default=ok; quarantine_hash_gate=ok; gpu_iommu_book_of_truth_gates=ok; trinity_policy_parity=ok; split_plane_attestation_policy_digest_gates=ok; inference_network_enable_path=none; ci_check=blocked; email_check=blocked; azure_vm_check=blocked.');
INSERT INTO iterations (agent,task_id,status,notes) VALUES ('sanhedrin','EMAIL-CHECK','skip','2026-04-26T19:14CEST: GitHub notifications Gmail query from:notifications@github.com subject:"Run failed" newer_than:1h blocked: MCP returned user cancelled.');
INSERT INTO iterations (agent,task_id,status,notes) VALUES ('sanhedrin','CI-CHECK','warning','2026-04-26T19:14CEST: gh run list blocked: cannot connect to api.github.com for TempleOS(codex/modernization-loop) and holyc-inference(main); failed-run triage unavailable.');
INSERT INTO iterations (agent,task_id,status,notes) VALUES ('sanhedrin','VM-CHECK','warning','2026-04-26T19:14CEST: Azure compile probe blocked: ssh azureuser@52.157.85.234 denied (Operation not permitted).');
INSERT INTO iterations (agent,task_id,status,notes) VALUES ('sanhedrin','AUDIT','warning','2026-04-26T19:14CEST Severity=WARNING loops_alive_by_heartbeat(mod=2026-04-26T19:12:26CEST inf=2026-04-26T19:13:50CEST san=2026-04-26T19:13:48CEST; all<=10m) ps_liveness_check=blocked(operation_not_permitted) localhost_restart_channel=blocked(host_localhost_unresolved) recent_builder_activity(last20:mod_pass=yes inf_pass=yes; latest_builder_db_ts=2026-04-23T12:06:44_stale) fail_streak5plus(mod=0 inf=0) repeat_task_streak_ge3(mod=0 inf=0) law5_code_output(mod_hc_sh_last5=6 inf_hc_last5=1 inf_hc_sh_py_last5=17) law1_nonholyc_core(mod=0 inf=0) law2_network_diff_hits=0 law4_float_hits=111(info) law6_open_cq=58(>=25) secure_local_default=ok quarantine_hash_gate=ok gpu_iommu_book_of_truth_gate=ok trinity_policy_parity=ok split_plane_attestation_policy_digest_gates=ok inference_network_enable_path=none ci_check=blocked(api.github.com_unreachable) email_check=blocked(user_cancelled_mcp) azure_vm_check=blocked(ssh_operation_not_permitted) cleanup_old_audit_md_deleted=0 airgap_policy_preserved no_ws8_execution.');

-- 2026-04-26T19:27:12+0200
INSERT INTO iterations (agent,task_id,status,notes) VALUES ('sanhedrin','AUDIT','warning','heartbeat_age_sec(mod=44 inf=3 san=4 via automation/logs/loop.heartbeat); ps_check=blocked_sandbox(op_not_permitted); recent_builder_db_latest(mod=2026-04-23T12:01:29 inf=2026-04-23T12:06:44 all_pass); fail_streak5plus(mod=0 inf=0); same_task_streak_ge3(mod=0 inf=0); law5_mod_hc_sh_last5=5(pass); law5_inf_hc_last5=1(pass) law5_inf_hc_sh_py_last5=17; law1_nonholyc_core_hits=0; law2_network_diff_hits=0; law4_float_hits=111(info); law6_open_cq=58(pass); secure_local_default=ok; quarantine_hash_gate=ok; gpu_iommu_book_of_truth_gates=ok; trinity_policy_parity=ok; split_plane_attestation_policy_digest_gates=ok; inference_network_enable_path=none; ci_check=blocked_no_network(api.github.com_unreachable); email_check=blocked_mcp_cancelled; azure_vm_compile_check=blocked_ssh_op_not_permitted; cleanup_old_audit_md_deleted=0; no_critical_violations.');

-- 2026-04-26T19:53:00+0200
INSERT INTO iterations (agent,task_id,status,notes) VALUES ('sanhedrin','EMAIL-CHECK','skip','2026-04-26T19:53CEST: GitHub notifications Gmail query from:notifications@github.com subject:"Run failed" newer_than:1h blocked: MCP returned user cancelled.');
INSERT INTO iterations (agent,task_id,status,notes) VALUES ('sanhedrin','CI-CHECK','warning','2026-04-26T19:53CEST: gh run list blocked: cannot connect to api.github.com for TempleOS(codex/modernization-loop) and holyc-inference(main); failed-run triage unavailable.');
INSERT INTO iterations (agent,task_id,status,notes) VALUES ('sanhedrin','VM-CHECK','warning','2026-04-26T19:53CEST: Azure compile probe blocked: ssh azureuser@52.157.85.234 denied (Operation not permitted).');
INSERT INTO iterations (agent,task_id,status,notes) VALUES ('sanhedrin','CLEANUP','pass','2026-04-26T19:53CEST: cleanup_old_audit_md_deleted=0.');
INSERT INTO iterations (agent,task_id,status,notes) VALUES ('sanhedrin','AUDIT','warning','2026-04-26T19:53CEST Severity=WARNING loops_alive_by_heartbeat(mod=4s inf=1s san=2s; all<=10m) ps_liveness_check=blocked(operation_not_permitted) builder_loop_activity=active(mod_iter=886@20260426-194726 inf_iter=869@20260426-193910) builder_db_write_errors=readonly_database8(mod,inf) latest_builder_db_ts_stale(mod=2026-04-23T12:01:29 inf=2026-04-23T12:06:44) fail_streak5plus(mod=0 inf=0) repeat_task_streak_ge3(mod=0 inf=0) law5_code_output(mod_hc_sh_last5=5 inf_hc_last5=1 inf_hc_sh_py_last5=17) law1_nonholyc_core(mod=0 inf=0) law2_network_diff_hits=0 law4_float_hits=111(info) law6_open_cq=58(>=25) secure_local_default=ok quarantine_hash_gate=ok gpu_iommu_book_of_truth_gate=ok trinity_policy_parity=ok split_plane_attestation_policy_digest_gates=ok inference_network_enable_path=none ci_check=blocked(api.github.com_unreachable) email_check=blocked(user_cancelled_mcp) azure_vm_check=blocked(ssh_operation_not_permitted) airgap_policy_preserved no_ws8_execution no_critical_violations.');
INSERT INTO iterations (agent,task_id,status,notes) VALUES ('sanhedrin','AUDIT','warning','2026-04-26T19:57CEST Severity=WARNING loops_alive_by_heartbeat(mod=2s inf=102s san=4s; all<=10m) ps_liveness_check=blocked(operation_not_permitted) recent_builder_db_ts_stale(mod=2026-04-23T12:01:29 inf=2026-04-23T12:06:44) recent_builder_pass_window(mod=43/43 inf=77/77) fail_streak5plus(mod=0 inf=0) repeat_task_streak_ge3(mod=0 inf=0;current=1/1) law5_code_output(mod_hc_sh_last5=5 inf_hc_sh_py_last5=16) law1_nonholyc_core(mod=0 inf=0) law2_network_diff_hits=0 law4_float_hits=111(info) law6_open_cq=58(>=25) secure_local_default=ok quarantine_hash_gate=ok gpu_iommu_book_of_truth_gate=ok trinity_policy_parity=ok split_plane_attestation_policy_digest_gates=ok inference_network_enable_path=none ci_check=blocked(api.github.com_unreachable) email_check=blocked(user_cancelled_mcp) azure_vm_check=blocked(ssh_operation_not_permitted) cleanup_old_audit_md_deleted=0 airgap_policy_preserved no_ws8_execution no_critical_violations.');
INSERT INTO iterations (agent,task_id,status,notes) VALUES ('sanhedrin','EMAIL-CHECK','skip','Gmail MCP query from:notifications@github.com subject:"Run failed" newer_than:1h returned user_cancelled_mcp_tool_call.');
INSERT INTO iterations (agent,task_id,status,notes) VALUES ('sanhedrin','CLEANUP','pass','cleanup_old_audit_md_deleted=0 (audit,audits,research mtime>7d).');
INSERT INTO iterations (agent,task_id,status,notes) VALUES ('sanhedrin','AUDIT','pass','2026-04-26T20:06CEST Severity=PASS heartbeat_age_sec(mod=2 inf=2 san=5; all<=10m) ps_liveness_check=blocked_sandbox(op_not_permitted) localhost_restart_channel=blocked(ssh_localhost_unavailable) recent_builder_pass_20(mod=20/20 inf=20/20) fail_streak5plus(mod=0 inf=0) repeat_task_streak_ge3(mod=0 inf=0) builder_code_rows_last20(mod=14/20 inf=12/20 inf_hc_rows=9/20) law5_mod_hc_sh_last5=5(pass) law5_inf_hc_last5=1(pass) law5_inf_hc_sh_py_last5=16 law1_nonholyc_core(mod=0 inf=0) law2_network_diff_hits=0 law4_float_hits=111(info) law6_open_cq=58(pass) secure_local_default=ok quarantine_hash_gate=ok gpu_iommu_book_of_truth_gates=ok trinity_policy_parity=ok split_plane_attestation_policy_digest_gates=ok inference_network_enable_path=none ci_check=blocked(api.github.com_unreachable; gh cli) ci_mcp=cancelled azure_vm_check=blocked(ssh_operation_not_permitted) email_check=cancelled_mcp airgap_policy_preserved no_ws8_execution no_critical_violations.');
INSERT INTO iterations (agent,task_id,status,notes) VALUES ('sanhedrin','EMAIL-CHECK','skip','2026-04-26T22:13CEST Gmail MCP query from:notifications@github.com subject:"Run failed" newer_than:1h returned user_cancelled_mcp_tool_call.');
INSERT INTO iterations (agent,task_id,status,notes) VALUES ('sanhedrin','CLEANUP','pass','2026-04-26T22:13CEST cleanup_old_audit_md_deleted=0 (audit,audits).');
INSERT INTO iterations (agent,task_id,status,notes) VALUES ('sanhedrin','AUDIT','warning','2026-04-26T22:13CEST heartbeat_age_sec(mod=3 inf=3 san=3 via automation/logs/loop.heartbeat; all<=10m) ps_liveness_check=blocked_sandbox(operation_not_permitted) recent_builder_pass_20(mod=13/13 inf=27/27) builder_code_rows(mod_hc_sh=13/13 inf_hc_sh_py=27/27 inf_hc=23/27) fail_streak5plus(mod=0 inf=0) same_task_streak_ge3(mod=0 inf=0) law5_mod_hc_sh_last5=5(pass) law5_inf_hc_last5=1(pass) law5_inf_hc_sh_py_last5=18 law1_nonholyc_core_hits=0 law2_network_diff_hits=0 law4_float_hits=111(info) law6_open_cq=58(pass) secure_local_default=ok quarantine_hash_gate=ok gpu_iommu_book_of_truth_gates=ok trinity_policy_parity=ok split_plane_attestation_policy_digest_gates=ok inference_network_enable_path=none ci_check=blocked_no_network(api.github.com_unreachable) email_check=blocked_mcp_user_cancelled vm_compile_check=blocked_ssh_operation_not_permitted airgap_policy_preserved no_ws8_execution db_write=blocked_readonly_database no_critical_violations.');
INSERT INTO iterations (agent,task_id,status,notes) VALUES ('sanhedrin','AUDIT','warning','2026-04-26T20:33CEST heartbeat_age_sec(mod=4 inf=2 san=2 via automation/logs/loop.heartbeat); ps_check=blocked_sandbox(op_not_permitted); recent_builder_activity_logs=active(TempleOS_CQ1734..CQ1743,Inference_IQ1671..IQ1680 all code-producing); recent_db_rows_stale(latest_builder_ts=2026-04-23 due readonly_db_writes); law5_mod_hc_sh_last5=5(pass); law5_inf_hc_last5=1(pass); law5_inf_hc_sh_py_last5=15; law1_nonholyc_core_hits=0; law2_network_diff_hits=0; law4_float_hits=111(info); law6_open_cq=58(pass); secure_local_default=ok; quarantine_hash_gate=ok; gpu_iommu_book_of_truth_gates=ok; trinity_policy_parity=ok; split_plane_attestation_policy_digest_gates=ok; inference_network_enable_path=none; ci_check=blocked(api.github.com_unreachable); email_check=blocked(mcp_unavailable_in_session); azure_vm_check=blocked(ssh_operation_not_permitted); no_critical_violations.');
INSERT INTO iterations (agent,task_id,status,notes) VALUES ('sanhedrin','AUDIT','warning','2026-04-26T20:48CEST heartbeat_age_sec(mod=4 inf=4 san=4) ps_check_blocked_sandbox(op_not_permitted) lock_files_present(mod=1 inf=1 san=1) recent_builder_pass20(mod=20/20 inf=20/20) fail_streak5plus(mod=0 inf=0) same_task_streak_ge3(mod=0 inf=0) law5_mod_hc_sh_last5=5(pass) law5_inf_hc_last5=12(pass) law1_nonholyc_core(mod=0 inf=0) law2_network_diff_hits=0 law4_float_hits=111(info) law6_open_cq=58(pass) secure_local_default=ok quarantine_hash_gate=ok gpu_iommu_book_of_truth_gate=ok trinity_policy_parity=ok split_plane_attestation_policy_digest_gates=ok inference_network_enable_path=none ci_check_blocked(api.github.com_unreachable) email_check_blocked(user_cancelled_mcp) azure_vm_check_blocked(ssh_operation_not_permitted) cleanup_old_audit_md_deleted=0 airgap_policy_preserved no_ws8_execution no_critical_violations.');
INSERT INTO iterations (agent,task_id,status,notes) VALUES ('sanhedrin','CI-CHECK','warning','2026-04-26T20:48CEST gh run list blocked: cannot connect to api.github.com for TempleOS(codex/modernization-loop) and holyc-inference(main); failed-run log triage unavailable.');
INSERT INTO iterations (agent,task_id,status,notes) VALUES ('sanhedrin','EMAIL-CHECK','skip','2026-04-26T20:48CEST Gmail MCP query from:notifications@github.com subject:"Run failed" newer_than:1h returned user cancelled MCP tool call.');
INSERT INTO iterations (agent,task_id,status,notes) VALUES ('sanhedrin','VM-CHECK','warning','2026-04-26T20:48CEST Azure compile probe blocked: ssh azureuser@52.157.85.234 denied (Operation not permitted).');
INSERT INTO iterations (agent,task_id,status,notes) VALUES ('sanhedrin','CLEANUP','pass','2026-04-26T20:48CEST cleanup_old_audit_md_deleted=0.');
INSERT INTO iterations (agent,task_id,status,notes) VALUES ('sanhedrin','AUDIT','warning','2026-04-26T21:26CEST heartbeat_age_sec(mod=4 inf=5 san=0 via automation/logs/loop.heartbeat; all<=10m) ps_liveness_check=blocked_sandbox(op_not_permitted; ssh_localhost_blocked) recent_builder_pass20(mod=20/20 inf=20/20 via automation/logs/*.final.txt) fail_streak5plus(mod=0 inf=0) same_task_streak_ge3(mod=0 inf=0) law5_mod_hc_sh_last5=5(pass) law5_inf_hc_last5=12(pass) law5_inf_hc_sh_py_last5=13 law1_nonholyc_core_hits=0 law2_network_diff_hits=0 law4_float_hits=111(info) law6_open_cq=58(pass) secure_local_default=ok quarantine_hash_gate=ok gpu_iommu_book_of_truth_gates=ok trinity_policy_parity=ok split_plane_attestation_policy_digest_gates=ok inference_network_enable_path=none ci_check=blocked_no_network(api.github.com_unreachable) email_check=blocked_mcp_cancelled azure_vm_check=blocked_ssh(operation_not_permitted) airgap_policy_preserved no_ws8_execution no_critical_violations.');
INSERT INTO iterations (agent,task_id,status,notes) VALUES ('sanhedrin','EMAIL-CHECK','skip','2026-04-26T21:46CEST Gmail MCP query from:notifications@github.com subject:"Run failed" newer_than:1h returned user_cancelled_mcp_tool_call.');
INSERT INTO iterations (agent,task_id,status,notes) VALUES ('sanhedrin','CI-CHECK','warning','2026-04-26T21:46CEST gh run list blocked: api.github.com unreachable for TempleOS(codex/modernization-loop) and holyc-inference(main); failed-run triage unavailable.');
INSERT INTO iterations (agent,task_id,status,notes) VALUES ('sanhedrin','VM-CHECK','warning','2026-04-26T21:46CEST Azure compile probe blocked: ssh azureuser@52.157.85.234 denied (Operation not permitted).');
INSERT INTO iterations (agent,task_id,status,notes) VALUES ('sanhedrin','CLEANUP','pass','2026-04-26T21:46CEST cleanup_old_audit_md_deleted=0.');
INSERT INTO iterations (agent,task_id,status,notes) VALUES ('sanhedrin','AUDIT','warning','2026-04-26T21:46CEST heartbeat_fresh(mod=2s inf=2s san=0s) ps_check_blocked_sandbox(op_not_permitted) builder_last_result_ok(mod_iter=901 inf_iter=882) central_db_builder_rows_stale(latest_mod=2026-04-23T12:01:29 latest_inf=2026-04-23T12:06:44) law5(mod_hc_sh_last5=5 inf_hc_last5=1 inf_hc_sh_py_last5=17) law1_nonholyc_core(mod=0 inf=0) law2_network_diff_hits=0 law4_float_hits=111(info) law6_open_cq=58(pass) secure_local_default=ok quarantine_hash_gate=ok gpu_iommu_book_of_truth_gates=ok trinity_policy_parity=ok split_plane_attestation_policy_digest_gates=ok inference_network_enable_paths=none fail_streak5plus(mod=0 inf=0) same_task_streak_ge3(mod=0 inf=0) airgap_policy_preserved no_ws8_execution ci_check=blocked email_check=cancelled_mcp vm_check=blocked_ssh no_critical_violations.');
